// Avoid pulling PUBLIC declarations with defaults into this translation unit,
// because Rcpp-exported definitions below carry defaults for autogenerated
// R wrappers. Yes, defaults are here in .cpp and in _public.hpp, so ensure
// they are synced!
#define RCPPTSKIT_IMPL
#include <RcppTskit.hpp>
#include <cstdint>
#include <exception>
#include <limits>
#include <vector>

namespace {
// namespace to keep the contents local to this file

constexpr tsk_flags_t kLoadSupportedFlags =
    TSK_LOAD_SKIP_TABLES | TSK_LOAD_SKIP_REFERENCE_SEQUENCE;

constexpr tsk_flags_t kCopyTablesSupportedFlags = TSK_COPY_FILE_UUID;

constexpr tsk_flags_t kTreeseqInitSupportedFlags =
    TSK_TS_INIT_BUILD_INDEXES | TSK_TS_INIT_COMPUTE_MUTATION_PARENTS;

// INTERNAL
// @title Validate load options
// @param options passed to load functions
// @param caller function name
// @details See
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_table_collection_load}.
//   The \code{rtsk_treeseq_load} and \code{rtsk_table_collection_load} allocate
//   objects, so we can't work with \code{TSK_NO_INIT}
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.TSK_NO_INIT}.
// @return Validated flags as bitwise options.
tsk_flags_t validate_load_options(const int options, const char *caller) {
  if (options < 0) {
    Rcpp::stop("%s does not support negative options", caller);
  }
  const tsk_flags_t flags = static_cast<tsk_flags_t>(options);
  const tsk_flags_t unsupported = flags & ~kLoadSupportedFlags;
  // ~ flips the bits in kLoadSupportedOptions
  if (unsupported != 0) {
    Rcpp::stop(
        "%s only supports load options TSK_LOAD_SKIP_TABLES (1 << 0) and "
        "TSK_LOAD_SKIP_REFERENCE_SEQUENCE (1 << 1); unsupported bits: 0x%X",
        caller, static_cast<unsigned int>(unsupported));
  }
  return flags;
}

// INTERNAL
// @title Validate copy tables options
// @param options passed to load functions
// @param caller function name
// @details See
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_copy_tables}
//   and
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_table_collection_copy}.
//   The \code{rtsk_treeseq_copy_tables} allocates table collection, so
//   we can't work with \code{TSK_NO_INIT}
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.TSK_NO_INIT}.
// @return Validated flags as bitwise options.
tsk_flags_t validate_copy_tables_options(const int options,
                                         const char *caller) {
  if (options < 0) {
    Rcpp::stop("%s does not support negative options", caller);
  }
  const tsk_flags_t flags = static_cast<tsk_flags_t>(options);
  if (flags & TSK_NO_INIT) {
    Rcpp::stop("%s does not support TSK_NO_INIT", caller);
  }
  const tsk_flags_t unsupported = flags & ~kCopyTablesSupportedFlags;
  if (unsupported != 0) {
    Rcpp::stop("%s only supports copy option TSK_COPY_FILE_UUID (1 << 0); "
               "unsupported bits: 0x%X",
               caller, static_cast<unsigned int>(unsupported));
  }
  return flags;
}

// INTERNAL
// @title Validate tree sequence initialisation options
// @param options passed to load functions
// @param caller function name
// @details See
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_init}.
//   \code{TSK_TAKE_OWNERSHIP} is unsupported because the input
//   table collection remains reachable via R external pointer (risk of
//   dangling alias / double-free), and because the ownership path of
//   \code{tsk_treeseq_free()} is based on C
//   \code{malloc()/free()}, while this wrapper manages that outer struct with
//   C++ \code{new()/delete()}.
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.TSK_TAKE_OWNERSHIP}.
// @return Validated flags as bitwise options.
tsk_flags_t validate_treeseq_init_options(const int options,
                                          const char *caller) {
  if (options < 0) {
    Rcpp::stop("%s does not support negative options", caller);
  }
  const tsk_flags_t flags = static_cast<tsk_flags_t>(options);
  if (flags & TSK_TAKE_OWNERSHIP) {
    Rcpp::stop("%s does not support TSK_TAKE_OWNERSHIP", caller);
  }
  const tsk_flags_t unsupported = flags & ~kTreeseqInitSupportedFlags;
  if (unsupported != 0) {
    Rcpp::stop(
        "%s only supports init options TSK_TS_INIT_BUILD_INDEXES (1 << 0) "
        "and TSK_TS_INIT_COMPUTE_MUTATION_PARENTS (1 << 1); unsupported "
        "bits: 0x%X",
        caller, static_cast<unsigned int>(unsupported));
  }
  return flags;
}

// INTERNAL
// @title Validate tskit flags
// @param options passed to tskit functions
// @param caller function name
// @details See for example
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_dump}
//   and
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_table_collection_dump},
//   which currently expects \code{0}.
// @return Validated flags as bitwise options.
tsk_flags_t validate_options(const int options, const tsk_flags_t supported,
                             const char *caller) {
  if (options < 0) {
    Rcpp::stop("%s does not support negative options", caller);
  }
  const tsk_flags_t flags = static_cast<tsk_flags_t>(options);
  const tsk_flags_t unsupported = flags & ~supported;
  if (unsupported != 0) {
    Rcpp::stop("%s only supports options 0x%X; unsupported bits: 0x%X", caller,
               static_cast<unsigned int>(supported),
               static_cast<unsigned int>(unsupported));
  }
  if (flags != 0) {
    Rcpp::stop("%s does not support non-zero options", caller);
  }
  return flags;
}

constexpr tsk_size_t kMaxBit64Integer64 =
    static_cast<tsk_size_t>(std::numeric_limits<int64_t>::max());

// INTERNAL
// @title Convert \code{Rcpp::Nullable} vector to empty-or-value vector
// @param value nullable vector from \code{R}
// @return Empty vector if \code{NULL}, otherwise converted vector.
template <typename VectorT>
VectorT nullable_to_vector_or_empty(const Rcpp::Nullable<VectorT> &value) {
  if (value.isNull()) {
    return VectorT();
  }
  return Rcpp::as<VectorT>(value);
}

// INTERNAL
// @title Convert \code{integer} vector to \code{tsk_id_t} vector
// @param ids \code{integer} values (must not have \code{NA} values).
// @param caller function name.
// @details \code{tsk_id_t} is \code{int32_t} (a standard integer)
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_id_t}
// @return ID values cast to \code{tsk_id_t}.
std::vector<tsk_id_t> int_vector_to_tsk_id_vector(
    const Rcpp::IntegerVector &ids,
    const char *caller = "int_vector_to_tsk_id_vector") {
  std::vector<tsk_id_t> out;
  out.reserve(ids.size());
  for (const int id : ids) {
    if (Rcpp::IntegerVector::is_na(id)) {
      Rcpp::stop("NA_integer_ values not allowed in %s", caller);
    }
    out.push_back(static_cast<tsk_id_t>(id));
  }
  return out;
}

// INTERNAL
// @title Wrap \code{C tsk_size_t / uint64_t} to \code{R bit64::integer64}
// @param value \code{C tsk_size_t / uint64_t} value
// @param caller function name
// @details \code{tsk_id_t} is \code{uint64_t}
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_size_t},
//   an unsigned 64 bit integer with range from 0 to 2^64 - 1
//   (that is, 0 to 18,446,744,073,709,551,615).
//   On the other hand, the R bit64::integer64 is
//   a signed 64 bit integer with range from -2^63 to 2^63 - 1
//   (that is, -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807)
// @return \code{R bit64::integer64} object.
SEXP rtsk_wrap_tsk_size_t_as_integer64(const tsk_size_t value,
                                       const char *caller) {
  const std::string value_str =
      std::to_string(static_cast<unsigned long long>(value));
  if (value > kMaxBit64Integer64) {
    const std::string max_str =
        std::to_string(static_cast<unsigned long long>(kMaxBit64Integer64));
    Rcpp::stop("%s returned tsk_size_t value %s, which exceeds "
               "bit64::integer64 maximum %s",
               caller, value_str.c_str(), max_str.c_str());
  }
  static Rcpp::Function as_integer64 =
      Rcpp::Environment::namespace_env("bit64")["as.integer64"];
  return as_integer64(value_str);
}

} // namespace

// TEST-ONLY
// @title Test helper for validating tskit flags
// @param options that will be validated
// @param supported integer bitmask for supported options
// @return Validated flags as integer.
// [[Rcpp::export]]
int test_validate_options(const int options, const int supported) {
  const tsk_flags_t out = validate_options(
      options, static_cast<tsk_flags_t>(supported), "test_validate_options");
  return static_cast<int>(out);
}

// TEST-ONLY
// @title Test helper for integer64 wrapping of \code{tsk_size_t}
// @param value character representation of unsigned integer
// @param force_range_error logical flag for testing range-check branch
// @return \code{R bit64::integer64} object.
// [[Rcpp::export]]
SEXP test_rtsk_wrap_tsk_size_t_as_integer64(
    const std::string value, const bool force_range_error = false) {
  unsigned long long parsed = 0;
  std::size_t parsed_chars = 0;
  try {
    parsed = std::stoull(value, &parsed_chars, 10);
  } catch (const std::exception &) {
    Rcpp::stop("value must be a valid base-10 unsigned integer string");
  }
  if (parsed_chars != value.size()) {
    Rcpp::stop("value must be a valid base-10 unsigned integer string");
  }
  const tsk_size_t tsk_value = static_cast<tsk_size_t>(parsed);
  if (force_range_error ||
      static_cast<unsigned long long>(tsk_value) != parsed) {
    Rcpp::stop("value is out of range for tsk_size_t");
  }
  return rtsk_wrap_tsk_size_t_as_integer64(
      tsk_value, "test_rtsk_wrap_tsk_size_t_as_integer64");
}

// PUBLIC
//' @title Report the version of installed kastore C API
//' @details The version is stored in the installed header \code{kastore.h}.
//' @return A named vector with three elements \code{major}, \code{minor}, and
//'   \code{patch}.
//' @examples
//' kastore_version()
//' @export
// [[Rcpp::export]]
Rcpp::IntegerVector kastore_version() {
  // Rcpp::_["major"] is shorthand for Rcpp::Named("major")
  return Rcpp::IntegerVector::create(Rcpp::_["major"] = KAS_VERSION_MAJOR,
                                     Rcpp::_["minor"] = KAS_VERSION_MINOR,
                                     Rcpp::_["patch"] = KAS_VERSION_PATCH);
}

// PUBLIC
//' @title Report the version of installed \code{tskit} C API
//' @details The version is defined in the installed header \code{tskit/core.h}.
//' @return A named vector with three elements \code{major}, \code{minor}, and
//'   \code{patch}.
//' @examples
//' tskit_version()
//' @export
// [[Rcpp::export]]
Rcpp::IntegerVector tskit_version() {
  return Rcpp::IntegerVector::create(Rcpp::_["major"] = TSK_VERSION_MAJOR,
                                     Rcpp::_["minor"] = TSK_VERSION_MINOR,
                                     Rcpp::_["patch"] = TSK_VERSION_PATCH);
}

// PUBLIC, wrapper for tsk_treeseq_load
// @title Load a tree sequence from a file
// @param filename a string specifying the full path of the tree sequence file.
// @param options passed to \code{tskit C} (see details and note that only
//   \code{TSK_LOAD_SKIP_TABLES} and \code{TSK_LOAD_SKIP_REFERENCE_SEQUENCE},
//   but not \code{TSK_NO_INIT}, are supported by this wrapper).
// @details This function calls
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_load}.
// @return An external pointer to tree sequence as a \code{tsk_treeseq_t}
//   object
// @seealso \code{\link{ts_load}} and
//   \code{\link[=TreeSequence]{TreeSequence$new}} on how this function is used
//   and presented to users.
// @examples
// ts_file <- system.file("examples/test.trees", package = "RcppTskit")
// ts_xptr <- RcppTskit:::rtsk_treeseq_load(ts_file)
// is(ts_xptr)
// ts_xptr
// RcppTskit:::rtsk_treeseq_get_num_nodes(ts_xptr)
// ts <- TreeSequence$new(xptr = ts_xptr)
// is(ts)
// [[Rcpp::export]]
SEXP rtsk_treeseq_load(const std::string &filename, const int options = 0) {
  const tsk_flags_t flags = validate_load_options(options, "rtsk_treeseq_load");
  // tsk_treeseq_t ts; // on stack, destroyed end of func, must free resources
  tsk_treeseq_t *ts_ptr = new tsk_treeseq_t(); // on heap, persists function
  // See also https://tskit.dev/tskit/docs/stable/c-api.html#api-structure
  int ret = tsk_treeseq_load(ts_ptr, filename.c_str(), flags);
  if (ret != 0) {
    tsk_treeseq_free(ts_ptr);
    delete ts_ptr;
    Rcpp::stop(tsk_strerror(ret));
  }
  // Wrap standard/raw ts_ptr for R as an external pointer handle (xptr)
  // "true" below means that R will call finaliser on garbage collection
  rtsk_treeseq_t ts_xptr(ts_ptr, true);
  return ts_xptr;
}

// PUBLIC, wrapper for tsk_table_collection_load
// @title Load a table collection from a file
// @param filename a string specifying the full path of the tree sequence file.
// @param options passed to \code{tskit C} (see details and note that only
//   \code{TSK_LOAD_SKIP_TABLES} and \code{TSK_LOAD_SKIP_REFERENCE_SEQUENCE},
//   but not \code{TSK_NO_INIT}, are supported by this wrapper).
// @details This function calls
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_table_collection_load}.
// @return An external pointer to table collection as a
//   \code{tsk_table_collection_t} object
// @seealso \code{\link{tc_load}} and
//   \code{\link[=TableCollection]{TableCollection$new}} on how this function is
//   used and presented to users.
// @examples
// ts_file <- system.file("examples/test.trees", package = "RcppTskit")
// tc_xptr <- RcppTskit:::rtsk_table_collection_load(ts_file)
// is(tc_xptr)
// tc_xptr
// RcppTskit:::rtsk_table_collection_print(tc_xptr)
// tc <- TableCollection$new(xptr = tc_xptr)
// is(tc)
// [[Rcpp::export]]
SEXP rtsk_table_collection_load(const std::string &filename,
                                const int options = 0) {
  const tsk_flags_t flags =
      validate_load_options(options, "rtsk_table_collection_load");
  tsk_table_collection_t *tc_ptr = new tsk_table_collection_t();
  int ret = tsk_table_collection_load(tc_ptr, filename.c_str(), flags);
  if (ret != 0) {
    tsk_table_collection_free(tc_ptr);
    delete tc_ptr;
    Rcpp::stop(tsk_strerror(ret));
  }
  // Wrap standard/raw tc_ptr for R as an external pointer handle (xptr)
  // "true" below means that R will call finaliser on garbage collection
  rtsk_table_collection_t tc_xptr(tc_ptr, true);
  return tc_xptr;
}

// PUBLIC, wrapper for tsk_treeseq_dump
// @title Write a tree sequence to a file
// @param ts an external pointer to tree sequence as a \code{tsk_treeseq_t}
//   object.
// @param filename a string specifying the full path of the tree sequence file.
// @param options passed to \code{tskit C} (see details and note that
//   these options are currently unused in \code{tskit} and should be \code{0}).
// @details This function calls
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_dump}.
// @return No return value; called for side effects.
// @examples
// ts_file <- system.file("examples/test.trees", package = "RcppTskit")
// ts_xptr <- RcppTskit:::rtsk_treeseq_load(ts_file)
// dump_file <- tempfile()
// RcppTskit:::rtsk_treeseq_dump(ts_xptr, dump_file)
// file.remove(dump_file)
// [[Rcpp::export]]
void rtsk_treeseq_dump(const SEXP ts, const std::string &filename,
                       const int options = 0) {
  const tsk_flags_t flags = validate_options(options, 0, "rtsk_treeseq_dump");
  rtsk_treeseq_t ts_xptr(ts);
  int ret = tsk_treeseq_dump(ts_xptr, filename.c_str(), flags);
  if (ret != 0) {
    Rcpp::stop(tsk_strerror(ret));
  }
}

// PUBLIC, wrapper for tsk_table_collection_dump
// @title Write a table collection to a file
// @param tc an external pointer to table collection as a
//   \code{tsk_table_collection_t} object.
// @param filename a string specifying the full path of the tree sequence file.
// @param options passed to \code{tskit C} (see details and note that
//   these options are currently unused in \code{tskit} and should be \code{0}).
// @details This function calls
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_table_collection_dump}.
// @return No return value; called for side effects.
// @examples
// ts_file <- system.file("examples/test.trees", package = "RcppTskit")
// tc_xptr <- RcppTskit:::rtsk_table_collection_load(ts_file)
// dump_file <- tempfile()
// RcppTskit:::rtsk_table_collection_dump(tc_xptr, dump_file)
// file.remove(dump_file)
// [[Rcpp::export]]
void rtsk_table_collection_dump(const SEXP tc, const std::string &filename,
                                const int options = 0) {
  const tsk_flags_t flags =
      validate_options(options, 0, "rtsk_table_collection_dump");
  rtsk_table_collection_t tc_xptr(tc);
  int ret = tsk_table_collection_dump(tc_xptr, filename.c_str(), flags);
  if (ret != 0) {
    Rcpp::stop(tsk_strerror(ret));
  }
}

// PUBLIC, wrapper for tsk_treeseq_copy_tables
// @title Copy a tree sequence's tables into a table collection
// @param ts an external pointer to tree sequence as a \code{tsk_treeseq_t}
//   object.
// @param options passed to \code{tskit C} (see details and note that
//   this wrapper does not support \code{TSK_NO_INIT}, but supports
//   \code{TSK_COPY_FILE_UUID}).
// @details This function calls
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_copy_tables}.
//   See also low-level Python-C call of \code{TreeSequence_dump_tables} at
//   \url{https://github.com/tskit-dev/tskit/blob/dc394d72d121c99c6dcad88f7a4873880924dd72/python/_tskitmodule.c#L5323}
// @return An external pointer to table collection as a
//   \code{tsk_table_collection_t} object
// @seealso \code{\link{tc_load}} and
//   \code{\link[=TreeSequence]{TreeSequence$dump_tables}} on how this function
//   is used and presented to users.
// @examples
// ts_file <- system.file("examples/test.trees", package = "RcppTskit")
// ts_xptr <- RcppTskit:::rtsk_treeseq_load(ts_file)
// tc_xptr <- RcppTskit:::rtsk_treeseq_copy_tables(ts_xptr)
// is(tc_xptr)
// tc_xptr
// RcppTskit:::rtsk_table_collection_print(tc_xptr)
// [[Rcpp::export]]
SEXP rtsk_treeseq_copy_tables(const SEXP ts, const int options = 0) {
  const tsk_flags_t flags =
      validate_copy_tables_options(options, "rtsk_treeseq_copy_tables");
  rtsk_treeseq_t ts_xptr(ts);
  tsk_table_collection_t *tc_ptr = new tsk_table_collection_t();
  int ret = tsk_treeseq_copy_tables(ts_xptr, tc_ptr, flags);
  if (ret != 0) {
    tsk_table_collection_free(tc_ptr);
    delete tc_ptr;
    Rcpp::stop(tsk_strerror(ret));
  }
  // Wrap standard/raw tc_ptr for R as an external pointer handle (xptr)
  // "true" below means that R will call finaliser on garbage collection
  rtsk_table_collection_t tc_xptr(tc_ptr, true);
  return tc_xptr;
}

// PUBLIC, wrapper for tsk_treeseq_init
// @title Initialise a tree sequence from a table collection
// @param tc an external pointer to table collection as a
//   \code{tsk_table_collection_t} object.
// @param options passed to \code{tskit C} (see details and note that
//   this wrapper supports
//   \code{TSK_TS_INIT_BUILD_INDEXES} and
//   \code{TSK_TS_INIT_COMPUTE_MUTATION_PARENTS}, but not
//   \code{TSK_TAKE_OWNERSHIP}).
//   \code{TSK_TAKE_OWNERSHIP} is unsupported because the input
//   table collection remains reachable via R external pointer (risk of
//   dangling alias / double-free), and because the ownership path of
//   \code{tsk_treeseq_free()} is based on C
//   \code{malloc()/free()}, while this wrapper manages that outer struct with
//   C++ \code{new()/delete()}.
// @details This function calls
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_init}.
//   See also low-level Python-C call of \code{TreeSequence_load_tables} at
//   \url{https://github.com/tskit-dev/tskit/blob/dc394d72d121c99c6dcad88f7a4873880924dd72/python/_tskitmodule.c#L5292}
// @return An external pointer to tree sequence as a \code{tsk_treeseq_t}
//   object
// @seealso \code{\link{tc_load}} and
//   \code{\link[=TableCollection]{TableCollection$tree_sequence}} on how this
//   function is used and presented to users.
// @examples
// ts_file <- system.file("examples/test.trees", package = "RcppTskit")
// tc_xptr <- RcppTskit:::rtsk_table_collection_load(ts_file)
// RcppTskit:::rtsk_table_collection_print(tc_xptr)
// ts_xptr <- RcppTskit:::rtsk_treeseq_init(tc_xptr)
// RcppTskit:::rtsk_treeseq_print(ts_xptr)
// [[Rcpp::export]]
SEXP rtsk_treeseq_init(const SEXP tc, const int options = 0) {
  const tsk_flags_t flags =
      validate_treeseq_init_options(options, "rtsk_treeseq_init");
  rtsk_table_collection_t tc_xptr(tc);
  tsk_treeseq_t *ts_ptr = new tsk_treeseq_t();
  int ret = tsk_treeseq_init(ts_ptr, tc_xptr, flags);
  if (ret != 0) {
    tsk_treeseq_free(ts_ptr);
    delete ts_ptr;
    Rcpp::stop(tsk_strerror(ret));
  }
  // Wrap standard/raw ts_ptr for R as an external pointer handle (xptr)
  // "true" below means that R will call finaliser on garbage collection
  rtsk_treeseq_t ts_xptr(ts_ptr, true);
  return ts_xptr;
}

// See tsk_treeseq_t inst/include/tskit/tskit/trees.h on which elements
// are there in a tsk_treeseq_t type.
// Here is a copy with comments on what we have implemented in RcppTskit:
//  * tsk_size_t num_trees; SCALAR, IMPLEMENTED HERE
//  * tsk_size_t num_samples; SCALAR, IMPLEMENTED HERE
//  * tsk_id_t *samples; ARRAY, TODO LATER #49
//  * bool time_uncalibrated; SKIPPED (for now) since we have time_units
//  * bool discrete_genome; SCALAR, IMPLEMENTED HERE
//  * bool discrete_time; SCALAR, IMPLEMENTED HERE
//  * double min_time; SCALAR, IMPLEMENTED HERE
//  * double max_time; SCALAR, IMPLEMENTED HERE
//  * double *breakpoints; ARRAY, TODO LATER #49
//  * tsk_id_t *sample_index_map; ARRAY, TODO LATER #49
//  * tsk_id_t *individual_nodes_mem; ARRAY, TODO LATER #49
//  * tsk_id_t **individual_nodes; ARRAY, TODO LATER #49
//  * tsk_size_t *individual_nodes_length; ARRAY, TODO LATER #49
//  * tsk_site_t *tree_sites_mem; ARRAY, TODO LATER #49
//  * tsk_site_t **tree_sites; ARRAY, TODO LATER #49
//  * tsk_size_t *tree_sites_length; ARRAY, TODO LATER #49
//  * tsk_mutation_t *site_mutations_mem; ARRAY, TODO LATER #49
//  * tsk_mutation_t **site_mutations; ARRAY, TODO LATER #49
//  * tsk_size_t *site_mutations_length; ARRAY, TODO LATER #49
//  * tsk_table_collection_t *tables; SKIPPED since we might look into
//    table-column arrays/vectors
//
// Here is the Python API summary
// https://tskit.dev/tskit/docs/stable/python-api.html#trees-and-tree-sequences
// https://tskit.dev/tskit/docs/stable/python-api.html#tskit.TreeSequence
// https://tskit.dev/tskit/docs/stable/python-api.html#tskit.TreeSequence.max_root_time
// is a scalar property (which we have strived to implement / mirror here),
// but this one requires table-column arrays, which we will look into in #49

// PUBLIC, wrapper for tsk_treeseq_get_num_provenances
// @describeIn rtsk_treeseq_summary Get the number of provenances in a tree
// sequence
// [[Rcpp::export]]
SEXP rtsk_treeseq_get_num_provenances(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  return rtsk_wrap_tsk_size_t_as_integer64(
      tsk_treeseq_get_num_provenances(ts_xptr),
      "rtsk_treeseq_get_num_provenances");
}

// PUBLIC, wrapper for tsk_treeseq_get_num_populations
// @describeIn rtsk_treeseq_summary Get the number of populations in a tree
// sequence
// [[Rcpp::export]]
SEXP rtsk_treeseq_get_num_populations(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  return rtsk_wrap_tsk_size_t_as_integer64(
      tsk_treeseq_get_num_populations(ts_xptr),
      "rtsk_treeseq_get_num_populations");
}

// PUBLIC, wrapper for tsk_treeseq_get_num_migrations
// @describeIn rtsk_treeseq_summary Get the number of migrations in a tree
// sequence
// [[Rcpp::export]]
SEXP rtsk_treeseq_get_num_migrations(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  return rtsk_wrap_tsk_size_t_as_integer64(
      tsk_treeseq_get_num_migrations(ts_xptr),
      "rtsk_treeseq_get_num_migrations");
}

// PUBLIC, wrapper for tsk_treeseq_get_num_individuals
// @describeIn rtsk_treeseq_summary Get the number of individuals in a tree
// sequence
// [[Rcpp::export]]
SEXP rtsk_treeseq_get_num_individuals(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  return rtsk_wrap_tsk_size_t_as_integer64(
      tsk_treeseq_get_num_individuals(ts_xptr),
      "rtsk_treeseq_get_num_individuals");
}

// PUBLIC, wrapper for tsk_treeseq_get_num_samples
// @describeIn rtsk_treeseq_summary Get the number of samples (of nodes) in a
// tree
//   sequence
// [[Rcpp::export]]
SEXP rtsk_treeseq_get_num_samples(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  return rtsk_wrap_tsk_size_t_as_integer64(tsk_treeseq_get_num_samples(ts_xptr),
                                           "rtsk_treeseq_get_num_samples");
}

// PUBLIC, wrapper for tsk_treeseq_get_num_nodes
// @describeIn rtsk_treeseq_summary Get the number of nodes in a tree sequence
// [[Rcpp::export]]
SEXP rtsk_treeseq_get_num_nodes(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  return rtsk_wrap_tsk_size_t_as_integer64(tsk_treeseq_get_num_nodes(ts_xptr),
                                           "rtsk_treeseq_get_num_nodes");
}

// PUBLIC, wrapper for tsk_treeseq_get_num_edges
// @describeIn rtsk_treeseq_summary Get the number of edges in a tree sequence
// [[Rcpp::export]]
SEXP rtsk_treeseq_get_num_edges(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  return rtsk_wrap_tsk_size_t_as_integer64(tsk_treeseq_get_num_edges(ts_xptr),
                                           "rtsk_treeseq_get_num_edges");
}

// PUBLIC, wrapper for tsk_treeseq_get_num_trees
// @describeIn rtsk_treeseq_summary Get the number of trees in a tree sequence
// [[Rcpp::export]]
SEXP rtsk_treeseq_get_num_trees(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  return rtsk_wrap_tsk_size_t_as_integer64(tsk_treeseq_get_num_trees(ts_xptr),
                                           "rtsk_treeseq_get_num_trees");
}

// PUBLIC, wrapper for tsk_treeseq_get_num_sites
// @describeIn rtsk_treeseq_summary Get the number of sites in a tree sequence
// [[Rcpp::export]]
SEXP rtsk_treeseq_get_num_sites(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  return rtsk_wrap_tsk_size_t_as_integer64(tsk_treeseq_get_num_sites(ts_xptr),
                                           "rtsk_treeseq_get_num_sites");
}

// PUBLIC, wrapper for tsk_treeseq_get_num_mutations
// @describeIn rtsk_treeseq_summary Get the number of mutations in a tree
// sequence
// [[Rcpp::export]]
SEXP rtsk_treeseq_get_num_mutations(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  return rtsk_wrap_tsk_size_t_as_integer64(
      tsk_treeseq_get_num_mutations(ts_xptr), "rtsk_treeseq_get_num_mutations");
}

// PUBLIC, wrapper for tsk_treeseq_get_sequence_length
// @describeIn rtsk_treeseq_summary Get the sequence length
// [[Rcpp::export]]
double rtsk_treeseq_get_sequence_length(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  return tsk_treeseq_get_sequence_length(ts_xptr);
}

// PUBLIC, wrapper for tsk_treeseq_get_discrete_genome
// @describeIn rtsk_treeseq_summary Get the discrete genome status
// [[Rcpp::export]]
bool rtsk_treeseq_get_discrete_genome(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  return tsk_treeseq_get_discrete_genome(ts_xptr);
}

// PUBLIC, wrapper for tsk_treeseq_has_reference_sequence
// @describeIn rtsk_treeseq_summary Does the tree sequence hold a reference
// genome
//   sequence
// @details Note that \code{tsk_treeseq_has_reference_sequence} is undocumented
//   method in the \code{tskit C} API (see \code{trees.h}), but documented in
//   \code{tskit Python} API
//   https://tskit.dev/tskit/docs/stable/python-api.html#tskit.TreeSequence.has_reference_sequence
// [[Rcpp::export]]
bool rtsk_treeseq_has_reference_sequence(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  return tsk_treeseq_has_reference_sequence(ts_xptr);
}

// PUBLIC, wrapper for tsk_treeseq_get_time_units and
// tsk_treeseq_get_time_units_length.
// @describeIn rtsk_treeseq_summary Get the time units string
// [[Rcpp::export]]
Rcpp::String rtsk_treeseq_get_time_units(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  const char *p = tsk_treeseq_get_time_units(ts_xptr);
  tsk_size_t n = tsk_treeseq_get_time_units_length(ts_xptr);
  std::string time_units;
  if (n > 0 && p != NULL) {
    time_units.assign(p, p + n);
  }
  return Rcpp::String(time_units);
}

// PUBLIC, wrapper for tsk_treeseq_get_discrete_time
// @describeIn rtsk_treeseq_summary Get the discrete time status
// [[Rcpp::export]]
bool rtsk_treeseq_get_discrete_time(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  return tsk_treeseq_get_discrete_time(ts_xptr);
}

// PUBLIC, wrapper for tsk_treeseq_get_min_time
// @describeIn rtsk_treeseq_summary Get the min time in node table and mutation
// table
// [[Rcpp::export]]
double rtsk_treeseq_get_min_time(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  return tsk_treeseq_get_min_time(ts_xptr);
}

// PUBLIC, wrapper for tsk_treeseq_get_max_time
// @describeIn rtsk_treeseq_summary Get the max time in node table and mutation
// table
// [[Rcpp::export]]
double rtsk_treeseq_get_max_time(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  return tsk_treeseq_get_max_time(ts_xptr);
}

// PUBLIC, wrapper for tsk_treeseq_get_file_uuid
// @describeIn rtsk_treeseq_summary Get the file uuid string
// [[Rcpp::export]]
Rcpp::String rtsk_treeseq_get_file_uuid(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  const char *p = tsk_treeseq_get_file_uuid(ts_xptr);
  if (p == NULL || p[0] == '\0') {
    return Rcpp::String(NA_STRING);
  }
  return Rcpp::String(p);
}

// PUBLIC, RcppTskit extension
// @name rtsk_treeseq_summary
// @title Summary of properties and number of records in a tree sequence
// @param ts an external pointer to tree sequence as a \code{tsk_treeseq_t}
//   object.
// @details These functions return the summary of properties and number of
//   records in a tree sequence, by calling
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_provenances},
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_populations},
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_migrations},
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_individuals},
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_samples},
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_nodes},
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_edges},
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_trees},
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_sites},
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_mutations},
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_sequence_length},
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_discrete_genome},
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_has_reference_sequence},
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_time_units},
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_discrete_time},
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_min_time},
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_max_time},
//   and
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_file_uuid},
// @return \code{rtsk_treeseq_summary} returns a named list with numbers and
//   values, while functions \code{rtsk_treeseq_*} return the number or value
//   for each item. Count-like values are returned as \code{R bit64::integer64}
//   to approach range in \code{C tsk_size_t / uint64_t}
//   (see \code{rtsk_wrap_tsk_size_t_as_integer64} for more details).
// @examples
// ts_file <- system.file("examples/test.trees", package = "RcppTskit")
// ts_xptr <- RcppTskit:::rtsk_treeseq_load(ts_file)
// RcppTskit:::rtsk_treeseq_summary(ts_xptr)
// RcppTskit:::rtsk_treeseq_get_num_provenances(ts_xptr)
// RcppTskit:::rtsk_treeseq_get_num_populations(ts_xptr)
// RcppTskit:::rtsk_treeseq_get_num_migrations(ts_xptr)
// RcppTskit:::rtsk_treeseq_get_num_individuals(ts_xptr)
// RcppTskit:::rtsk_treeseq_get_num_samples(ts_xptr)
// RcppTskit:::rtsk_treeseq_get_num_nodes(ts_xptr)
// RcppTskit:::rtsk_treeseq_get_num_edges(ts_xptr)
// RcppTskit:::rtsk_treeseq_get_num_trees(ts_xptr)
// RcppTskit:::rtsk_treeseq_get_num_sites(ts_xptr)
// RcppTskit:::rtsk_treeseq_get_num_mutations(ts_xptr)
// RcppTskit:::rtsk_treeseq_get_sequence_length(ts_xptr)
// RcppTskit:::rtsk_treeseq_get_discrete_genome(ts_xptr)
// RcppTskit:::rtsk_treeseq_has_reference_sequence(ts_xptr)
// RcppTskit:::rtsk_treeseq_get_time_units(ts_xptr)
// RcppTskit:::rtsk_treeseq_get_discrete_time(ts_xptr)
// RcppTskit:::rtsk_treeseq_get_min_time(ts_xptr)
// RcppTskit:::rtsk_treeseq_get_max_time(ts_xptr)
// RcppTskit:::rtsk_treeseq_get_file_uuid(ts_xptr)
// EXTENSION: composite summary helper (no single tsk_* equivalent).
// [[Rcpp::export]]
Rcpp::List rtsk_treeseq_summary(const SEXP ts) {
  return Rcpp::List::create(
      Rcpp::_["num_provenances"] = rtsk_treeseq_get_num_provenances(ts),
      Rcpp::_["num_populations"] = rtsk_treeseq_get_num_populations(ts),
      Rcpp::_["num_migrations"] = rtsk_treeseq_get_num_migrations(ts),
      Rcpp::_["num_individuals"] = rtsk_treeseq_get_num_individuals(ts),
      Rcpp::_["num_samples"] = rtsk_treeseq_get_num_samples(ts),
      Rcpp::_["num_nodes"] = rtsk_treeseq_get_num_nodes(ts),
      Rcpp::_["num_edges"] = rtsk_treeseq_get_num_edges(ts),
      Rcpp::_["num_trees"] = rtsk_treeseq_get_num_trees(ts),
      Rcpp::_["num_sites"] = rtsk_treeseq_get_num_sites(ts),
      Rcpp::_["num_mutations"] = rtsk_treeseq_get_num_mutations(ts),
      Rcpp::_["sequence_length"] = rtsk_treeseq_get_sequence_length(ts),
      Rcpp::_["discrete_genome"] = rtsk_treeseq_get_discrete_genome(ts),
      Rcpp::_["has_reference_sequence"] =
          rtsk_treeseq_has_reference_sequence(ts),
      Rcpp::_["time_units"] = rtsk_treeseq_get_time_units(ts),
      Rcpp::_["discrete_time"] = rtsk_treeseq_get_discrete_time(ts),
      Rcpp::_["min_time"] = rtsk_treeseq_get_min_time(ts),
      Rcpp::_["max_time"] = rtsk_treeseq_get_max_time(ts),
      Rcpp::_["file_uuid"] = rtsk_treeseq_get_file_uuid(ts));
}

// PUBLIC, RcppTskit extension
// @title Get the length of metadata in a tree sequence and its tables
// @param ts tree sequence as a \code{\link{TreeSequence}} object or
//   an external pointer to tree sequence as a \code{tsk_treeseq_t} object.
// @details This function returns the length of metadata stored on the tree
//   sequence and in each table by calling
//   \code{ts->tables->metadata_length} and
//   \code{ts->tables->x->metadata_length} on each table \code{x}, e.g.,
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_population_table_t.metadata_length}.
// @return A named list with the length of metadata as \code{R bit64::integer64}
//   values.
// @examples
// ts_file <- system.file("examples/test.trees", package = "RcppTskit")
// ts_xptr <- RcppTskit:::rtsk_treeseq_load(ts_file)
// RcppTskit:::rtsk_treeseq_metadata_length(ts_xptr)
// [[Rcpp::export]]
Rcpp::List rtsk_treeseq_metadata_length(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  const tsk_table_collection_t *tables = ts_xptr->tables;
  return Rcpp::List::create(
      // The tree sequence metadata is the tables collection metadata and
      // tsk_treeseq_get_metadata_length() returns self->tables->metadata_length
      // Rcpp::_["ts"] =
      //    static_cast<int>(tsk_treeseq_get_metadata_length(ts_xptr)),
      // hence we just use that here
      Rcpp::_["ts"] = rtsk_wrap_tsk_size_t_as_integer64(
          tables->metadata_length,
          "rtsk_treeseq_metadata_length/tables->metadata_length"),
      Rcpp::_["populations"] = rtsk_wrap_tsk_size_t_as_integer64(
          tables->populations.metadata_length,
          "rtsk_treeseq_metadata_length/tables->populations.metadata_length"),
      Rcpp::_["migrations"] = rtsk_wrap_tsk_size_t_as_integer64(
          tables->migrations.metadata_length,
          "rtsk_treeseq_metadata_length/tables->migrations.metadata_length"),
      Rcpp::_["individuals"] = rtsk_wrap_tsk_size_t_as_integer64(
          tables->individuals.metadata_length,
          "rtsk_treeseq_metadata_length/tables->individuals.metadata_length"),
      Rcpp::_["nodes"] = rtsk_wrap_tsk_size_t_as_integer64(
          tables->nodes.metadata_length,
          "rtsk_treeseq_metadata_length/tables->nodes.metadata_length"),
      Rcpp::_["edges"] = rtsk_wrap_tsk_size_t_as_integer64(
          tables->edges.metadata_length,
          "rtsk_treeseq_metadata_length/tables->edges.metadata_length"),
      Rcpp::_["sites"] = rtsk_wrap_tsk_size_t_as_integer64(
          tables->sites.metadata_length,
          "rtsk_treeseq_metadata_length/tables->sites.metadata_length"),
      Rcpp::_["mutations"] = rtsk_wrap_tsk_size_t_as_integer64(
          tables->mutations.metadata_length,
          "rtsk_treeseq_metadata_length/tables->mutations.metadata_length"));
}

// INTERNAL (for now)
// # nocov start
// TODO: Metadata notes if we do anything with metadata #36
//       https://github.com/HighlanderLab/RcppTskit/issues/36
// This is how we would get metadata, but it will be raw bytes,
// so would have to work with schema and codes ...
// ts_file <- system.file("examples/test.trees", package = "RcppTskit")
// ts_xptr <- RcppTskit:::rtsk_treeseq_load(ts_file)
// RcppTskit:::rtsk_treeseq_get_metadata(ts_xptr)
// slendr::ts_metadata(slim_ts)
Rcpp::String rtsk_treeseq_get_metadata(const SEXP ts) {
  rtsk_treeseq_t ts_xptr(ts);
  const char *p = tsk_treeseq_get_metadata(ts_xptr);
  tsk_size_t n = tsk_treeseq_get_metadata_length(ts_xptr);
  std::string metadata;
  if (n > 0 && p != NULL) {
    metadata.assign(p, p + n);
  }
  return Rcpp::String(metadata);
}
// # nocov end

// TODO: Metadata notes if we do anything with metadata #36
//       https://github.com/HighlanderLab/RcppTskit/issues/36
// int rtsk_treeseq_metadata_schema_length(const SEXP ts) {
//  rtsk_treeseq_t ts_xptr(ts);
//  return static_cast<int>(tsk_treeseq_get_metadata_schema_length(ts_xptr));
// }
// TODO: test the above function
// TODO: document the above function
// TODO: expose the above function to R, including TreeSequence method

// TODO: Develop tsk_treeseq_get_metadata
// TODO: Metadata notes if we do anything with metadata #36
//       https://github.com/HighlanderLab/RcppTskit/issues/36

// See tsk_treeseq_t inst/include/tskit/tskit/tables.h on which elements
// are there in a tsk_table_collection_t type.
// Here is a copy with comments on what we have implemented in RcppTskit:
//   * double sequence_length; SCALAR, IMPLEMENTED HERE
//   * char *file_uuid; "SCALAR", IMPLEMENTED HERE
//   * char *time_units; "SCALAR", IMPLEMENTED HERE
//   * tsk_size_t time_units_length; IMPLEMENTED HERE (as part of the above)
// TODO: Metadata notes if we do anything with metadata #36
//       https://github.com/HighlanderLab/RcppTskit/issues/36
//   * char *metadata; "SCALAR", TODO --> rtsk_table_collection_metadata
//   * tsk_size_t metadata_length; SCALAR, TODO as part of the above
// TODO: Metadata notes if we do anything with metadata #36
//       https://github.com/HighlanderLab/RcppTskit/issues/36
//   * char *metadata_schema; "SCALAR", TODO -->
//     rtsk_table_collection_metadata_schema
//   * tsk_size_t metadata_schema_length; SCALAR, TODO as part of the above
//   * tsk_reference_sequence_t reference_sequence; TODO?
//   * tsk_individual_table_t individuals; TABLE, SKIP OR TODO LATER #49
//   * tsk_node_table_t nodes; TABLE, SKIP OR TODO LATER #49
//   * tsk_edge_table_t edges; TABLE, SKIP OR TODO LATER #49
//   * tsk_migration_table_t migrations; TABLE, SKIP OR TODO LATER #49
//   * tsk_site_table_t sites; TABLE, SKIP OR TODO LATER #49
//   * tsk_mutation_table_t mutations; TABLE, SKIP OR TODO LATER #49
//   * tsk_population_table_t populations; TABLE, SKIP OR TODO LATER #49
//   * tsk_provenance_table_t provenances; TABLE, SKIP OR TODO LATER #49
//   * struct {
//       tsk_id_t *edge_insertion_order;
//       tsk_id_t *edge_removal_order;
//       tsk_size_t num_edges;
//    *} indexes; SKIPPED (for now)
//
// Here is the Python summary
// https://tskit.dev/tskit/docs/stable/python-api.html#sec-tables-api-table-collection
// https://tskit.dev/tskit/docs/stable/python-api.html#tskit.TableCollection

// PUBLIC, RcppTskit extension
// @describeIn rtsk_table_collection_summary Get the number of provenances
//   in a table collection
// [[Rcpp::export]]
SEXP rtsk_table_collection_get_num_provenances(const SEXP tc) {
  rtsk_table_collection_t tc_xptr(tc);
  return rtsk_wrap_tsk_size_t_as_integer64(
      tc_xptr->provenances.num_rows,
      "rtsk_table_collection_get_num_provenances");
}

// PUBLIC, RcppTskit extension
// @describeIn rtsk_table_collection_summary Get the number of populations
//   in a table collection
// [[Rcpp::export]]
SEXP rtsk_table_collection_get_num_populations(const SEXP tc) {
  rtsk_table_collection_t tc_xptr(tc);
  return rtsk_wrap_tsk_size_t_as_integer64(
      tc_xptr->populations.num_rows,
      "rtsk_table_collection_get_num_populations");
}

// PUBLIC, RcppTskit extension
// @describeIn rtsk_table_collection_summary Get the number of migrations
//   in a table collection
// [[Rcpp::export]]
SEXP rtsk_table_collection_get_num_migrations(const SEXP tc) {
  rtsk_table_collection_t tc_xptr(tc);
  return rtsk_wrap_tsk_size_t_as_integer64(
      tc_xptr->migrations.num_rows, "rtsk_table_collection_get_num_migrations");
}

// PUBLIC, RcppTskit extension
// @describeIn rtsk_table_collection_summary Get the number of individuals
//   in a table collection
// [[Rcpp::export]]
SEXP rtsk_table_collection_get_num_individuals(const SEXP tc) {
  rtsk_table_collection_t tc_xptr(tc);
  return rtsk_wrap_tsk_size_t_as_integer64(
      tc_xptr->individuals.num_rows,
      "rtsk_table_collection_get_num_individuals");
}

// PUBLIC, RcppTskit extension
// @describeIn rtsk_table_collection_summary Get the number of nodes
//   in a table collection
// [[Rcpp::export]]
SEXP rtsk_table_collection_get_num_nodes(const SEXP tc) {
  rtsk_table_collection_t tc_xptr(tc);
  return rtsk_wrap_tsk_size_t_as_integer64(
      tc_xptr->nodes.num_rows, "rtsk_table_collection_get_num_nodes");
}

// PUBLIC, RcppTskit extension
// @describeIn rtsk_table_collection_summary Get the number of edges
//   in a table collection
// [[Rcpp::export]]
SEXP rtsk_table_collection_get_num_edges(const SEXP tc) {
  rtsk_table_collection_t tc_xptr(tc);
  return rtsk_wrap_tsk_size_t_as_integer64(
      tc_xptr->edges.num_rows, "rtsk_table_collection_get_num_edges");
}

// PUBLIC, RcppTskit extension
// @describeIn rtsk_table_collection_summary Get the number of sites
//   in a table collection
// [[Rcpp::export]]
SEXP rtsk_table_collection_get_num_sites(const SEXP tc) {
  rtsk_table_collection_t tc_xptr(tc);
  return rtsk_wrap_tsk_size_t_as_integer64(
      tc_xptr->sites.num_rows, "rtsk_table_collection_get_num_sites");
}

// PUBLIC, RcppTskit extension
// @describeIn rtsk_table_collection_summary Get the number of mutations
//   in a table collection
// [[Rcpp::export]]
SEXP rtsk_table_collection_get_num_mutations(const SEXP tc) {
  rtsk_table_collection_t tc_xptr(tc);
  return rtsk_wrap_tsk_size_t_as_integer64(
      tc_xptr->mutations.num_rows, "rtsk_table_collection_get_num_mutations");
}

// PUBLIC, RcppTskit extension
// @describeIn rtsk_table_collection_summary Get the sequence length
// [[Rcpp::export]]
double rtsk_table_collection_get_sequence_length(const SEXP tc) {
  rtsk_table_collection_t tc_xptr(tc);
  return tc_xptr->sequence_length;
}

// PUBLIC, wrapper for tsk_table_collection_has_reference_sequence
// @describeIn rtsk_table_collection_summary Does the table collection hold a
//   reference genome sequence
// @details Note that tsk_table_collection_has_reference_sequence is
//   undocumented method in the tskit C API (see tables.h),
//   but documented in tskit Python API
//   https://tskit.dev/tskit/docs/stable/python-api.html#tskit.TableCollection.has_reference_sequence
// [[Rcpp::export]]
bool rtsk_table_collection_has_reference_sequence(const SEXP tc) {
  rtsk_table_collection_t tc_xptr(tc);
  return tsk_table_collection_has_reference_sequence(tc_xptr);
}

// PUBLIC, RcppTskit extension
// @describeIn rtsk_table_collection_summary Get the time units string
// [[Rcpp::export]]
Rcpp::String rtsk_table_collection_get_time_units(const SEXP tc) {
  rtsk_table_collection_t tc_xptr(tc);
  const char *p = tc_xptr->time_units;
  tsk_size_t n = tc_xptr->time_units_length;
  std::string time_units;
  if (n > 0 && p != NULL) {
    time_units.assign(p, p + n);
  }
  return Rcpp::String(time_units);
}

// PUBLIC, RcppTskit extension
// @describeIn rtsk_table_collection_summary Get the file uuid string
// [[Rcpp::export]]
Rcpp::String rtsk_table_collection_get_file_uuid(const SEXP tc) {
  rtsk_table_collection_t tc_xptr(tc);
  if (tc_xptr->file_uuid == NULL || tc_xptr->file_uuid[0] == '\0') {
    return Rcpp::String(NA_STRING);
  }
  return Rcpp::String(tc_xptr->file_uuid);
}

// PUBLIC, wrapper for tsk_table_collection_has_index
// @describeIn rtsk_table_collection_summary Is the table collection indexed
// [[Rcpp::export]]
bool rtsk_table_collection_has_index(const SEXP tc, const int options = 0) {
  const tsk_flags_t flags =
      validate_options(options, 0, "rtsk_table_collection_has_index");
  rtsk_table_collection_t tc_xptr(tc);
  return tsk_table_collection_has_index(tc_xptr, flags);
}

// PUBLIC, wrapper for tsk_table_collection_build_index
// @title Build indexes for a table collection
// @param tc an external pointer to table collection as a
//   \code{tsk_table_collection_t} object.
// @param options passed to \code{tskit C}, currently unused and should be
//   set to \code{0}.
// @details This function calls
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_table_collection_build_index}.
// @return No return value; called for side effects.
// @examples
// ts_file <- system.file("examples/test.trees", package = "RcppTskit")
// tc_xptr <- RcppTskit:::rtsk_table_collection_load(ts_file)
// RcppTskit:::rtsk_table_collection_has_index(tc_xptr)
// RcppTskit:::rtsk_table_collection_drop_index(tc_xptr)
// RcppTskit:::rtsk_table_collection_has_index(tc_xptr)
// RcppTskit:::rtsk_table_collection_build_index(tc_xptr)
// RcppTskit:::rtsk_table_collection_has_index(tc_xptr)
// [[Rcpp::export]]
void rtsk_table_collection_build_index(const SEXP tc, const int options = 0) {
  const tsk_flags_t flags =
      validate_options(options, 0, "rtsk_table_collection_build_index");
  rtsk_table_collection_t tc_xptr(tc);
  int ret = tsk_table_collection_build_index(tc_xptr, flags);
  if (ret != 0) {
    Rcpp::stop(tsk_strerror(ret));
  }
}

// PUBLIC, wrapper for tsk_table_collection_drop_index
// @title Drop indexes for a table collection
// @param tc an external pointer to table collection as a
//   \code{tsk_table_collection_t} object.
// @param options passed to \code{tskit C}, currently unused and should be
//   set to \code{0}.
// @details This function calls
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_table_collection_drop_index}.
// @return No return value; called for side effects.
// @examples
// ts_file <- system.file("examples/test.trees", package = "RcppTskit")
// tc_xptr <- RcppTskit:::rtsk_table_collection_load(ts_file)
// RcppTskit:::rtsk_table_collection_has_index(tc_xptr)
// RcppTskit:::rtsk_table_collection_drop_index(tc_xptr)
// RcppTskit:::rtsk_table_collection_has_index(tc_xptr)
// [[Rcpp::export]]
void rtsk_table_collection_drop_index(const SEXP tc, const int options = 0) {
  const tsk_flags_t flags =
      validate_options(options, 0, "rtsk_table_collection_drop_index");
  rtsk_table_collection_t tc_xptr(tc);
  int ret = tsk_table_collection_drop_index(tc_xptr, flags);
  // tsk_table_collection_drop_index() currently documents always returning 0;
  // so we test for possible future failures, but we cannot unit-test this
  // path. # nocov start
  if (ret != 0) {
    Rcpp::stop(tsk_strerror(ret));
  }
  // # nocov end
}

// TODO: Do we have to add TableCollection$sort() method? #99
//       https://github.com/HighlanderLab/RcppTskit/issues/99

// TODO: Do we need any other method on table collection to produce a valid
//       ts? #100
//       https://github.com/HighlanderLab/RcppTskit/issues/100

// PUBLIC, RcppTskit extension
// @title Summary of properties and number of records in a table collection
// @param tc an external pointer to table collection as a
//   \code{tsk_table_collection_t} object.
// @param options passed to \code{tskit C}, currently unused and should be
//   set to \code{0}.
// @details These functions return the summary of properties and number of
//   records in a table collection, by accessing its elements and/or calling
// \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_table_collection_has_index}
// @return \code{rtsk_table_collection_summary} returns a named list with
//   numbers and values, while functions \code{rtsk_table_collection_*} return
//   the number or value for each item. Count-like values are returned as
//   \code{R bit64::integer64} to approach range in \code{C tsk_size_t /
//   uint64_t} (see \code{rtsk_wrap_tsk_size_t_as_integer64} for more
//   details).
// @examples
// ts_file <- system.file("examples/test.trees", package = "RcppTskit")
// tc_xptr <- RcppTskit:::rtsk_table_collection_load(ts_file)
// RcppTskit:::rtsk_table_collection_summary(tc_xptr)
// RcppTskit:::rtsk_table_collection_get_num_provenances(ts_xptr)
// RcppTskit:::rtsk_table_collection_get_num_populations(ts_xptr)
// RcppTskit:::rtsk_table_collection_get_num_migrations(ts_xptr)
// RcppTskit:::rtsk_table_collection_get_num_individuals(ts_xptr)
// RcppTskit:::rtsk_table_collection_get_num_samples(ts_xptr)
// RcppTskit:::rtsk_table_collection_get_num_nodes(ts_xptr)
// RcppTskit:::rtsk_table_collection_get_num_edges(ts_xptr)
// RcppTskit:::rtsk_table_collection_get_num_trees(ts_xptr)
// RcppTskit:::rtsk_table_collection_get_num_sites(ts_xptr)
// RcppTskit:::rtsk_table_collection_get_num_mutations(ts_xptr)
// RcppTskit:::rtsk_table_collection_get_sequence_length(tc_xptr)
// RcppTskit:::rtsk_table_collection_has_reference_sequence(tc_xptr)
// RcppTskit:::rtsk_table_collection_get_time_units(tc_xptr)
// RcppTskit:::rtsk_table_collection_get_file_uuid(tc_xptr)
// RcppTskit:::rtsk_table_collection_has_index(tc_xptr)
// [[Rcpp::export]]
Rcpp::List rtsk_table_collection_summary(const SEXP tc) {
  return Rcpp::List::create(
      Rcpp::_["num_provenances"] =
          rtsk_table_collection_get_num_provenances(tc),
      Rcpp::_["num_populations"] =
          rtsk_table_collection_get_num_populations(tc),
      Rcpp::_["num_migrations"] = rtsk_table_collection_get_num_migrations(tc),
      Rcpp::_["num_individuals"] =
          rtsk_table_collection_get_num_individuals(tc),
      Rcpp::_["num_nodes"] = rtsk_table_collection_get_num_nodes(tc),
      Rcpp::_["num_edges"] = rtsk_table_collection_get_num_edges(tc),
      Rcpp::_["num_sites"] = rtsk_table_collection_get_num_sites(tc),
      Rcpp::_["num_mutations"] = rtsk_table_collection_get_num_mutations(tc),
      Rcpp::_["sequence_length"] =
          rtsk_table_collection_get_sequence_length(tc),
      Rcpp::_["has_reference_sequence"] =
          rtsk_table_collection_has_reference_sequence(tc),
      Rcpp::_["time_units"] = rtsk_table_collection_get_time_units(tc),
      Rcpp::_["file_uuid"] = rtsk_table_collection_get_file_uuid(tc),
      Rcpp::_["has_index"] = rtsk_table_collection_has_index(tc));
}

// PUBLIC, RcppTskit extension
// @title Get the length of metadata in a table collection and its tables
// @param tc an external pointer to table collection as a
//   \code{tsk_table_collection_t} object.
// @return A named list with the length of metadata as \code{R
// bit64::integer64}
//   values to approach range in \code{C tsk_size_t / uint64_t}
//   (see \code{rtsk_wrap_tsk_size_t_as_integer64} for more details).
// @examples
// ts_file <- system.file("examples/test.trees", package = "RcppTskit")
// tc_xptr <- RcppTskit:::rtsk_table_collection_load(ts_file)
// RcppTskit:::rtsk_table_collection_metadata_length(tc_xptr)
// EXTENSION: metadata-length summary across tables (no single tsk_*
// equivalent).
// [[Rcpp::export]]
Rcpp::List rtsk_table_collection_metadata_length(const SEXP tc) {
  rtsk_table_collection_t tc_xptr(tc);
  return Rcpp::List::create(
      Rcpp::_["tc"] = rtsk_wrap_tsk_size_t_as_integer64(
          tc_xptr->metadata_length, "rtsk_table_collection_metadata_length/"
                                    "tc_xptr->metadata_length"),
      Rcpp::_["populations"] = rtsk_wrap_tsk_size_t_as_integer64(
          tc_xptr->populations.metadata_length,
          "rtsk_table_collection_metadata_length/"
          "tc_xptr->populations.metadata_length"),
      Rcpp::_["migrations"] = rtsk_wrap_tsk_size_t_as_integer64(
          tc_xptr->migrations.metadata_length,
          "rtsk_table_collection_metadata_length/"
          "tc_xptr->migrations.metadata_length"),
      Rcpp::_["individuals"] = rtsk_wrap_tsk_size_t_as_integer64(
          tc_xptr->individuals.metadata_length,
          "rtsk_table_collection_metadata_length/"
          "tc_xptr->individuals.metadata_length"),
      Rcpp::_["nodes"] = rtsk_wrap_tsk_size_t_as_integer64(
          tc_xptr->nodes.metadata_length,
          "rtsk_table_collection_metadata_length/"
          "tc_xptr->nodes.metadata_length"),
      Rcpp::_["edges"] = rtsk_wrap_tsk_size_t_as_integer64(
          tc_xptr->edges.metadata_length,
          "rtsk_table_collection_metadata_length/"
          "tc_xptr->edges.metadata_length"),
      Rcpp::_["sites"] = rtsk_wrap_tsk_size_t_as_integer64(
          tc_xptr->sites.metadata_length,
          "rtsk_table_collection_metadata_length/"
          "tc_xptr->sites.metadata_length"),
      Rcpp::_["mutations"] = rtsk_wrap_tsk_size_t_as_integer64(
          tc_xptr->mutations.metadata_length,
          "rtsk_table_collection_metadata_length/"
          "tc_xptr->mutations.metadata_length"));
}

// TODO: Metadata notes if we do anything with metadata #36
//       https://github.com/HighlanderLab/RcppTskit/issues/36
// int rtsk_table_collection_metadata_schema_length(const SEXP tc) {
//   rtsk_table_collection_t tc_xptr(tc);
//   return static_cast<int>(tc_xptr->metadata_schema_length);
// }
// TODO: test the above function
// TODO: document the above function
// TODO: expose the above function to R, including TableCollection method

// TODO: Develop rtsk_table_collection_metadata_schema
// TODO: Metadata notes if we do anything with metadata #36
//       https://github.com/HighlanderLab/RcppTskit/issues/36

// PUBLIC, wrapper for tsk_individual_table_add_row
// @title Add a row to the individual table in a table collection
// @param tc an external pointer to table collection as a
//   \code{tsk_table_collection_t} object.
// @param flags passed to \code{tskit C}.
// @param location numeric vector with the location of the new individual
//   (can be \code{NULL}).
// @param parents integer vector with parent individual IDs
//   (can be \code{NULL}).
// @param metadata raw vector with metadata bytes
//   (can be \code{NULL}).
// @details This function calls
//   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_individual_table_add_row}
//   on the individuals table of \code{tc}.
// @return The 0-based row ID of the newly added individual.
// @examples
// ts_file <- system.file("examples/test.trees", package = "RcppTskit")
// tc_xptr <- RcppTskit:::rtsk_table_collection_load(ts_file)
// n_before <- RcppTskit:::rtsk_table_collection_get_num_individuals(tc_xptr)
// tc_py <- RcppTskit:::rtsk_table_collection_r_to_py(tc_xptr)
// tc_py$individuals$max_rows
// tc_py$individuals["flags"]
// tc_py$individuals["location"]
// tc_py$individuals["location_offset"]
// tc_py$individuals["parents"]
// tc_py$individuals["parents_offset"]
// tc_py$individuals["metadata"]
// tc_py$individuals["metadata_offset"]
// new_id <- RcppTskit:::rtsk_individual_table_add_row(tc = tc_xptr)
// new_id <- RcppTskit:::rtsk_individual_table_add_row(tc = tc_xptr,
//   location = c(5, 8))
// new_id <- RcppTskit:::rtsk_individual_table_add_row(tc = tc_xptr, flags = 0L,
//   location = c(1, 2))
// new_id <- RcppTskit:::rtsk_individual_table_add_row(tc = tc_xptr, flags = 1L,
//   location = c(11, 3))
// new_id <- RcppTskit:::rtsk_individual_table_add_row(tc = tc_xptr, flags = 2L,
//   location = c(7, 8), parents = c(0L))
// new_id <- RcppTskit:::rtsk_individual_table_add_row(tc = tc_xptr, flags = 3L,
//   location = c(2, 11), parents = c(1L, 3L), metadata = charToRaw("abc"))
// n_after <- RcppTskit:::rtsk_table_collection_get_num_individuals(tc_xptr)
// new_id == as.integer(n_before) && n_after == n_before + 3L
// tc_py <- RcppTskit:::rtsk_table_collection_r_to_py(tc_xptr)
// tc_py$individuals$max_rows
// tc_py$individuals["flags"]
// tc_py$individuals["location"]
// tc_py$individuals["location_offset"]
// tc_py$individuals["parents"]
// tc_py$individuals["parents_offset"]
// tc_py$individuals["metadata"]
// tc_py$individuals["metadata_offset"]
// [[Rcpp::export]]
int rtsk_individual_table_add_row(
    const SEXP tc, const int flags = 0,
    const Rcpp::Nullable<Rcpp::NumericVector> location = R_NilValue,
    const Rcpp::Nullable<Rcpp::IntegerVector> parents = R_NilValue,
    const Rcpp::Nullable<Rcpp::RawVector> metadata = R_NilValue) {
  if (flags < 0) {
    Rcpp::stop("rtsk_individual_table_add_row does not support negative flags");
  }
  const tsk_flags_t row_flags = static_cast<tsk_flags_t>(flags);
  rtsk_table_collection_t tc_xptr(tc);

  // Prepare inputs for tskit C tsk_individual_table_add_row() in expected form
  const Rcpp::NumericVector location_vec =
      nullable_to_vector_or_empty<Rcpp::NumericVector>(location);
  const tsk_size_t location_length =
      static_cast<tsk_size_t>(location_vec.size());
  const double *location_ptr =
      location_length > 0 ? REAL(location_vec) : nullptr;

  const Rcpp::IntegerVector parents_in =
      nullable_to_vector_or_empty<Rcpp::IntegerVector>(parents);
  const std::vector<tsk_id_t> parents_vec =
      int_vector_to_tsk_id_vector(parents_in, "rtsk_individual_table_add_row");
  const tsk_size_t parents_length = static_cast<tsk_size_t>(parents_vec.size());
  const tsk_id_t *parents_ptr =
      parents_length > 0 ? parents_vec.data() : nullptr;

  const Rcpp::RawVector metadata_vec =
      nullable_to_vector_or_empty<Rcpp::RawVector>(metadata);
  const tsk_size_t metadata_length =
      static_cast<tsk_size_t>(metadata_vec.size());
  const char *metadata_ptr =
      metadata_length > 0 ? reinterpret_cast<const char *>(RAW(metadata_vec))
                          : nullptr;

  const tsk_id_t row_id = tsk_individual_table_add_row(
      &tc_xptr->individuals, row_flags, location_ptr, location_length,
      parents_ptr, parents_length, metadata_ptr, metadata_length);
  if (row_id < 0) {
    Rcpp::stop(tsk_strerror(row_id));
  }
  return static_cast<int>(row_id);
}
