# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_validate_options <- function(options, supported) {
    .Call(`_RcppTskit_test_validate_options`, options, supported)
}

test_rtsk_wrap_tsk_size_t_as_integer64 <- function(value, force_range_error = FALSE) {
    .Call(`_RcppTskit_test_rtsk_wrap_tsk_size_t_as_integer64`, value, force_range_error)
}

#' @title Report the version of installed kastore C API
#' @details The version is stored in the installed header \code{kastore.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'   \code{patch}.
#' @examples
#' kastore_version()
#' @export
kastore_version <- function() {
    .Call(`_RcppTskit_kastore_version`)
}

#' @title Report the version of installed \code{tskit} C API
#' @details The version is defined in the installed header \code{tskit/core.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'   \code{patch}.
#' @examples
#' tskit_version()
#' @export
tskit_version <- function() {
    .Call(`_RcppTskit_tskit_version`)
}

rtsk_treeseq_load <- function(filename, options = 0L) {
    .Call(`_RcppTskit_rtsk_treeseq_load`, filename, options)
}

rtsk_table_collection_load <- function(filename, options = 0L) {
    .Call(`_RcppTskit_rtsk_table_collection_load`, filename, options)
}

rtsk_treeseq_dump <- function(ts, filename, options = 0L) {
    invisible(.Call(`_RcppTskit_rtsk_treeseq_dump`, ts, filename, options))
}

rtsk_table_collection_dump <- function(tc, filename, options = 0L) {
    invisible(.Call(`_RcppTskit_rtsk_table_collection_dump`, tc, filename, options))
}

rtsk_treeseq_copy_tables <- function(ts, options = 0L) {
    .Call(`_RcppTskit_rtsk_treeseq_copy_tables`, ts, options)
}

rtsk_treeseq_init <- function(tc, options = 0L) {
    .Call(`_RcppTskit_rtsk_treeseq_init`, tc, options)
}

rtsk_treeseq_get_num_provenances <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_provenances`, ts)
}

rtsk_treeseq_get_num_populations <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_populations`, ts)
}

rtsk_treeseq_get_num_migrations <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_migrations`, ts)
}

rtsk_treeseq_get_num_individuals <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_individuals`, ts)
}

rtsk_treeseq_get_num_samples <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_samples`, ts)
}

rtsk_treeseq_get_num_nodes <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_nodes`, ts)
}

rtsk_treeseq_get_num_edges <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_edges`, ts)
}

rtsk_treeseq_get_num_trees <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_trees`, ts)
}

rtsk_treeseq_get_num_sites <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_sites`, ts)
}

rtsk_treeseq_get_num_mutations <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_mutations`, ts)
}

rtsk_treeseq_get_sequence_length <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_sequence_length`, ts)
}

rtsk_treeseq_get_discrete_genome <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_discrete_genome`, ts)
}

rtsk_treeseq_has_reference_sequence <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_has_reference_sequence`, ts)
}

rtsk_treeseq_get_time_units <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_time_units`, ts)
}

rtsk_treeseq_get_discrete_time <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_discrete_time`, ts)
}

rtsk_treeseq_get_min_time <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_min_time`, ts)
}

rtsk_treeseq_get_max_time <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_max_time`, ts)
}

rtsk_treeseq_get_file_uuid <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_file_uuid`, ts)
}

rtsk_treeseq_summary <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_summary`, ts)
}

rtsk_treeseq_metadata_length <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_metadata_length`, ts)
}

rtsk_table_collection_get_sequence_length <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_get_sequence_length`, tc)
}

rtsk_table_collection_has_reference_sequence <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_has_reference_sequence`, tc)
}

rtsk_table_collection_get_time_units <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_get_time_units`, tc)
}

rtsk_table_collection_get_file_uuid <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_get_file_uuid`, tc)
}

rtsk_table_collection_has_index <- function(tc, options = 0L) {
    .Call(`_RcppTskit_rtsk_table_collection_has_index`, tc, options)
}

rtsk_table_collection_build_index <- function(tc, options = 0L) {
    invisible(.Call(`_RcppTskit_rtsk_table_collection_build_index`, tc, options))
}

rtsk_table_collection_drop_index <- function(tc, options = 0L) {
    invisible(.Call(`_RcppTskit_rtsk_table_collection_drop_index`, tc, options))
}

rtsk_table_collection_summary <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_summary`, tc)
}

rtsk_table_collection_metadata_length <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_metadata_length`, tc)
}

test_tsk_bug_assert_c <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_bug_assert_c`))
}

test_tsk_bug_assert_cpp <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_bug_assert_cpp`))
}

test_tsk_trace_error_c <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_trace_error_c`))
}

test_tsk_trace_error_cpp <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_trace_error_cpp`))
}

tsk_trace_errors_defined <- function() {
    .Call(`_RcppTskit_tsk_trace_errors_defined`)
}

test_rtsk_treeseq_copy_tables_forced_error <- function(ts) {
    .Call(`_RcppTskit_test_rtsk_treeseq_copy_tables_forced_error`, ts)
}

test_rtsk_treeseq_init_forced_error <- function(tc) {
    .Call(`_RcppTskit_test_rtsk_treeseq_init_forced_error`, tc)
}

test_rtsk_table_collection_build_index_forced_error <- function(tc) {
    invisible(.Call(`_RcppTskit_test_rtsk_table_collection_build_index_forced_error`, tc))
}

